# HTTP configuration
quarkus.http.port=8080
%dev.quarkus.http.port=8888

# Application name
quarkus.application.name=miles-and-smiles-a2a

# A2A Server Configuration
quarkus.agentcard.protocol=JSONRPC
a2a.base-url=http://localhost:8888/
%prod.a2a.base-url=http://miles-and-smiles-a2a.miles-and-smiles.svc.cluster.local/

# LLM Provider Configuration
quarkus.langchain4j.chat-model.provider=openai

# AI model configuration
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true
quarkus.log.level=INFO

quarkus.langchain4j.openai.api-key=${OPENAI_API_KEY}
quarkus.langchain4j.openai.chat-model.model-name=gpt-4o
quarkus.langchain4j.openai.chat-model.temperature=0
quarkus.langchain4j.openai.timeout=180s

# Logging configuration
%dev.quarkus.log.category."dev.langchain4j".level=DEBUG
%dev.quarkus.log.category."dev.langchain4j.agentic".level=DEBUG
%dev.quarkus.log.category."com.demo".level=DEBUG

# Container image configuration
quarkus.container-image.registry=quay.io
quarkus.container-image.group=kevindubois
quarkus.container-image.name=miles-and-smiles-a2a
quarkus.container-image.tag=latest

# Kubernetes Config - Enable secrets
%prod.quarkus.kubernetes-config.enabled=true
%prod.quarkus.kubernetes-config.secrets.enabled=true
%prod.quarkus.kubernetes-config.secrets=miles-and-smiles
%prod.quarkus.kubernetes.namespace=miles-and-smiles

quarkus.podman.platform=linux/amd64